spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: prod
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html

security:
  #配置放行的目录和方法
  ignored: /api/*,/css/*,/js/*,/images/*,/fonts/*,/font-awesome/*

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

