spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

security:
  #配置放行的目录和方法
  ignored: /api/*,/css/*,/js/*,/images/*,/fonts/*,/font-awesome/*

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  file: logs/si.log
  level:
    com.lyu.csdndemo.sys.dao: debug
